#!/bin/ash

fw_zone_id() {
    echo $(uci show firewall | grep -E "@zone\[\d+\]\.name=\'$1\'" | head -n 1| grep -o -E '\d+')
}


# LAN dhcp server

uci set network.lan.ipaddr='192.168.1.10'
uci set network.lan.netmask='255.255.255.0'
uci commit network

uci set system.@system[0].hostname='Dlink DIR-320 B1'
uci commit system

uci -q delete dhcp.lan.ignore
uci set dhcp.lan='dhcp'
uci set dhcp.lan.interface='lan'
uci set dhcp.lan.start='100'
uci set dhcp.lan.limit='150'
uci set dhcp.lan.leasetime='12h'
uci set dhcp.lan.dhcpv4='server'
uci set dhcp.lan.dhcpv6='server'
uci set dhcp.lan.ra='server'
uci set dhcp.lan.ra_slaac='1'
uci -q delete dhcp.lan.ra_flags
uci add_list dhcp.lan.ra_flags='managed-config'
uci add_list dhcp.lan.ra_flags='other-config'

uci set dhcp.wan='dhcp'
uci set dhcp.wan.interface='wan'
uci set dhcp.wan.ignore='1'

uci set dhcp.odhcpd='odhcpd'
uci set dhcp.odhcpd.maindhcp='0'
uci set dhcp.odhcpd.loglevel='4'

uci commit dhcp

# LAN DNS servers

uci -q delete dhcp.@dnsmasq[0].nonwildcard
uci -q delete dhcp.@dnsmasq[0].boguspriv
uci -q delete dhcp.@dnsmasq[0].filterwin2k
uci -q delete dhcp.@dnsmasq[0].filter_aaaa
uci -q delete dhcp.@dnsmasq[0].filter_a
uci -q delete dhcp.@dnsmasq[0].nonegcache
uci -q delete dhcp.@dnsmasq[0].address

uci set dhcp.@dnsmasq[0].allservers='1'
uci add_list dhcp.@dnsmasq[0].interface='lan'

uci -q delete dhcp.@dnsmasq[0].server
uci add_list dhcp.@dnsmasq[0].server='94.140.14.14'
uci add_list dhcp.@dnsmasq[0].server='1.1.1.1'
uci add_list dhcp.@dnsmasq[0].server='8.8.8.8'
uci add_list dhcp.@dnsmasq[0].server='77.88.8.8'
uci add_list dhcp.@dnsmasq[0].server='2a10:50c0::ad1:ff'
uci add_list dhcp.@dnsmasq[0].server='2a02:6b8::feed:0ff'

uci commit dhcp

# SSH

uci set dropbear.@dropbear[0]='dropbear'
uci set dropbear.@dropbear[0].Port='22'
uci set dropbear.@dropbear[0].RootPasswordAuth='on'

uci commit dropbear

# Web interface

uci -q delete uhttpd.main.listen_http
uci add_list uhttpd.main.listen_http='0.0.0.0:80'
uci add_list uhttpd.main.listen_http='[::]:80'

uci -q delete uhttpd.main.listen_https
uci add_list uhttpd.main.listen_https='0.0.0.0:443'
uci add_list uhttpd.main.listen_https='[::]:443'

uci set uhttpd.main.redirect_https='0'
uci set uhttpd.main.script_timeout='60'
uci set uhttpd.main.network_timeout='30'
uci set uhttpd.main.http_keepalive='20'
uci set uhttpd.main.tcp_keepalive='1'

uci commit uhttpd

# Time sync

uci -q delete system.ntp.server
uci add_list system.ntp.server='0.ru.pool.ntp.org'
uci add_list system.ntp.server='1.ru.pool.ntp.org'
uci add_list system.ntp.server='2.ru.pool.ntp.org'
uci add_list system.ntp.server='3.ru.pool.ntp.org'

uci commit system

# WIFI

uci set wireless.radio0='wifi-device'
uci set wireless.radio0.type='mac80211'
uci set wireless.radio0.path='platform/10180000.wmac'
uci set wireless.radio0.channel='1'
uci set wireless.radio0.band='2g'
uci set wireless.radio0.htmode='HT20'
uci set wireless.radio0.country='RU'
uci set wireless.radio0.cell_density='0'
uci set wireless.default_radio0='wifi-iface'
uci set wireless.default_radio0.device='radio0'
uci set wireless.default_radio0.network='lan'
uci set wireless.default_radio0.mode='ap'
uci set wireless.default_radio0.ssid='Dlink320OpenWrt23'
uci set wireless.default_radio0.encryption='owe'

uci -q delete wireless.radio0.disabled
uci -q delete wireless.default_radio0.disabled

uci commit wireless

# PPPoE

uci set network.wan_pppoe='interface'
uci set network.wan_pppoe.auto='0'
uci set network.wan_pppoe.proto='pppoe'
uci set network.wan_pppoe.device='eth0.2'
uci set network.wan_pppoe.ipv6='auto'
# uci set network.wan_pppoe.peerdns='0'

uci add_list "firewall.@zone[$(fw_zone_id wan)].network"='wan_pppoe'

uci commit firewall
uci commit network

# The proper method to reload all daemon configurations affected by UCI changes
/etc/init.d/network restart
/etc/init.d/dnsmasq restart
/etc/init.d/uhttpd restart
/etc/init.d/sysntpd restart
/etc/init.d/firewall restart

# wifi settings are not applied until it's fully restarted
wifi down
wifi up
