name: Build

on:
  push:
    branches: ['v*']

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        id: login
        uses: docker/login-action@v3
        continue-on-error: true
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        id: pull_image
        continue-on-error: true
        if: success()
        run: |
          . ./set_env
          docker pull ghcr.io/${{ github.repository }}/$DOCKER_IMAGE_NAME:$OPENWRT_VERSION

      - name: Build Image
        if: steps.pull_image.outcome != 'success'
        id: build_image
        run: |
          . ./set_env
          echo "OPENWRT_DIR=$OPENWRT_DIR" >> $GITHUB_ENV
          echo "OPENWRT_TARGET=$OPENWRT_TARGET" >> $GITHUB_ENV
          ./build_scripts/build_docker_image

      - name: Upload Image
        if: steps.build_image.outcome == 'success'
        continue-on-error: true
        run: |
          . ./set_env
          docker tag $DOCKER_IMAGE_NAME:$OPENWRT_VERSION ghcr.io/${{ github.repository }}/$DOCKER_IMAGE_NAME:$OPENWRT_VERSION
          docker push ghcr.io/${{ github.repository }}/$DOCKER_IMAGE_NAME:$OPENWRT_VERSION

      - name: Run build
        run: |
          . ./set_env
          ./build_scripts/run_docker_container

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.OPENWRT_DIR }}/bin/targets/${{ env.OPENWRT_TARGET }}/*.bin
          tag_name: $OPENWRT_DIR-${{ github.sha }}
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.CONTENT_ACCESS_SECRET }}
